# Generated by Django 5.0.6 on 2024-06-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dash", "0003_alter_product_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
